### ISSUE TITLE
ClickOnce FileAssociation arguments not forwarded to application

### ISSUE THREAD

**Issue by nzain** [dotnet/deployment-tools#113] opened 2021-04-29 10:59 UTC
### Description
After migration of a .Net Framework (4.7.2) WPF ClickOnce application to `net5.0-windows` the original API for file associations seems to be missing and I could not find detailed documentation about [file associations](https://docs.microsoft.com/en-us/visualstudio/deployment/how-to-create-file-associations-for-a-clickonce-application?view=vs-2019) in .Net 5.

The definition of the `<FileAssociation>` can be done with the ClickOnce wizard. ClickOnce will generate a file association element in the manifest file that is registered with windows during setup. That works, windows associates the particular file type with my application, shows the correct icon and starts my new .Net 5 application. However, I can't retrieve the file name of the opened file: Previously, in a .Net Framework app deployed via ClickOnce you would access the clicked file via
```cs
string[] activationData = AppDomain.CurrentDomain.SetupInformation.ActivationArguments?.ActivationData;
```
However, the `AppDomainSetup` type of `net5.0-windows` does not have `ActivationArguments` anymore:

- [net48 documentation](https://docs.microsoft.com/de-de/dotnet/api/system.appdomainsetup?view=netframework-4.8)
- [net50 documentation](https://docs.microsoft.com/de-de/dotnet/api/system.appdomainsetup?view=net-5.0)

Alternatives I've tried:

- `Environment.GetCommandLineArgs()[1..]` but that never worked for ClickOnce apps. You skip index 0, because that is the executable itself. That hasn't changed and the resulting string array is empty. Put differently: associated file double clicks do not translate into command line arguments.
- override the `Application.OnStartup(StartupEventArgs e)` method and check `e.Args`. This is empty as well.

**Q: how do I programmatically retrieve the clicked filename with .Net 5 onwards?**

### Configuration

- .Net 5.0.5
- I'm running windows 10 Version 2004 (build 19041.928)
- relevant csproj properties:
```xml
    <TargetFramework>net5.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <UseWPF>true</UseWPF>
```

### Regression?
Yes, the API was working on .Net Framework (confirmed on 4.7.2).
The API does not even exist on .Net 5.0 or at least not in the same place.

### Other information
My publish profile xml looks like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<!--
https://go.microsoft.com/fwlink/?LinkID=208121. 
-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <ApplicationRevision>3</ApplicationRevision>
    <ApplicationVersion>2.0.0.*</ApplicationVersion>
    <BootstrapperEnabled>True</BootstrapperEnabled>
    <Configuration>Release</Configuration>
    <CreateWebPageOnPublish>False</CreateWebPageOnPublish>
    <GenerateManifests>True</GenerateManifests>
    <Install>True</Install>
    <InstallFrom>Unc</InstallFrom>
    <InstallUrl>\\... my server URI...</InstallUrl>
    <IsRevisionIncremented>True</IsRevisionIncremented>
    <IsWebBootstrapper>False</IsWebBootstrapper>
    <MapFileExtensions>True</MapFileExtensions>
    <OpenBrowserOnPublish>False</OpenBrowserOnPublish>
    <Platform>Any CPU</Platform>
    <ProductName>my application</ProductName>
    <PublishDir>\\... my server URI...</PublishDir>
    <PublishUrl>\\... my server URI...</PublishUrl>
    <PublisherName>my company</PublisherName>
    <PublishProtocol>ClickOnce</PublishProtocol>
    <PublishReadyToRun>False</PublishReadyToRun>
    <PublishSingleFile>False</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>False</SelfContained>
    <SignatureAlgorithm>(none)</SignatureAlgorithm>
    <SignManifests>False</SignManifests>
    <SuiteName>my suite</SuiteName>
    <TargetCulture>en</TargetCulture>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UpdateEnabled>True</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateRequired>False</UpdateRequired>
    <WebPageFileName>Publish.htm</WebPageFileName>
    <History>False|2021-04-29T09:00:58.3417469Z;False|2021-04-29T11:00:17.1405860+02:00;False|2021-04-29T10:59:51.1134217+02:00;</History>
  </PropertyGroup>
  <ItemGroup>
    <BootstrapperPackage Include="Microsoft.NetCore.DesktopRuntime.5.0.x64">
      <Install>true</Install>
      <ProductName>.NET Desktop Runtime 5.0.5 (x64)</ProductName>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <FileAssociation Include=".track">
      <Visible>False</Visible>
      <Description>My description</Description>
      <Progid>My.App.Id</Progid>
      <DefaultIcon>App.ico</DefaultIcon>
    </FileAssociation>
  </ItemGroup>
</Project>
```

**Comment by NikolaMilosavljevic** [comment] 2021-05-05 20:53
[Triage] @NikolaMilosavljevic, please check if this will be supported with https://github.com/dotnet/deployment-tools/issues/53 or https://github.com/dotnet/deployment-tools/issues/27, or if it needs a different workaround.

**Comment by Mark123New** [comment] 2021-05-25 11:00
I'm currently facing the same problem. 

Besides the points of the thread owner, i also tried to get the directory the application was started from - the folder that contains the associated file that was clicked, not the assembly folder - but with no success. This would have been sufficient for me as i don't expect more than one file of my associated type inside a project folder.

I still don't get the point why MS releases a utilty that enables the user to associate a file type to an application without any possibility to open the associated file that has been clicked?!?

#53 and #27 don't seem to be a real option. In my opinion, the opened file should be available from Environment.GetCommandLineArgs(). This would make using the ClickOnce stuff behave more like other applications that don't use ClickOnce.

**Comment by nzain** [comment] 2021-07-12 15:38
If #53 provides any workaround, that would be better than nothing (current state). The previous API was not intuitive, but at least documented. Once you get it working, you never touch it again.

However, #53 was first triaged for net7.0 (not the target seems to be 6.0). This issue, however, is not rated at all.

I cannot work around it and customers are angry... thus:

I would prefer a quick and dirty net6.0 solution over a clean net7.0 solution! Please don't forget us.

**Comment by nzain** [comment] 2021-08-16 05:02
@NikolaMilosavljevic what are your thoughts on this? Do you think it can be fixed together with one of the other tickets? Is there any workaround that keeps the auto-update-on-startup functionality (this is the only reason why we use ClickOnce)? And how could the timeline look like? Net6 is around the corner and this is broken for quite a while now.

**Comment by NikolaosWakem** [comment] 2021-08-17 14:25
Does anyone know why the developers of .NET5 and .NET6 are still refusing to put ActivationUri somewhere or even explain any other way to access it?

We all have to ship a 4.7.2 ClickOnceeapp with a packaged .NET 5 app just to do

var uri = ApplicationDeployment.CurrentDeployment.ActivationUri
process.start("theNet5App.exe", "--uri" +uri )

Which is so silly.

**Comment by nzain** [comment] 2022-11-22 14:42
While PR #208 (re?)enables several environment variables (including the activation URI), it does not help with file associations. Double click on an associated file opens the click once app, but all kinds of argument arrays (and the activation URI as well) are empty in the windows app scenario. Multiple dotnet versions (5-7) have passed along and this is not addressed :(

Visual Studio allows to define file associations over all the versions and its just broken/useless with modern dontet.

**Comment by NikolaMilosavljevic** [comment] 2022-11-22 18:08
@nzain I have created a different issue to track activation arguments: https://github.com/dotnet/deployment-tools/issues/236

But the root cause is the same and the solution would cover both scenarios, that are not a lot different.

Once the fix is in place, the application will be able to access the data in environment variables.

**Comment by NikolaMilosavljevic** [comment] 2023-01-30 22:01
Fix in PR: https://github.com/dotnet/deployment-tools/pull/245

**Comment by nzain** [comment] 2023-07-12 08:19
I think this has been fixed already, but I could not find any documentation how to access the filename in my app.

**Closed** 2024-01-05 21:24 UTC
